// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class V1beta1ChallengeProvider
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1ChallengeProvider class.
        /// </summary>
        public V1beta1ChallengeProvider()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1ChallengeProvider class.
        /// </summary>
        public V1beta1ChallengeProvider(V1beta1DNSChallengeProvider dns = default(V1beta1DNSChallengeProvider), V1beta1HTTPChallengeProvider http = default(V1beta1HTTPChallengeProvider))
        {
            Dns = dns;
            Http = http;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dns")]
        public V1beta1DNSChallengeProvider Dns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "http")]
        public V1beta1HTTPChallengeProvider Http { get; set; }

    }
}
