// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class V1beta1DNSChallengeProvider
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1DNSChallengeProvider
        /// class.
        /// </summary>
        public V1beta1DNSChallengeProvider()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1DNSChallengeProvider
        /// class.
        /// </summary>
        /// <param name="provider">DNS Provider from the list
        /// https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md</param>
        public V1beta1DNSChallengeProvider(string credentialSecretName = default(string), string provider = default(string))
        {
            CredentialSecretName = credentialSecretName;
            Provider = provider;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "credentialSecretName")]
        public string CredentialSecretName { get; set; }

        /// <summary>
        /// Gets or sets DNS Provider from the list
        /// https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md
        /// </summary>
        [JsonProperty(PropertyName = "provider")]
        public string Provider { get; set; }

    }
}
