using k8s.Models;

// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// IngressBackend describes all endpoints for a given service and port.
    /// </summary>
    public partial class V1beta1IngressBackend
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1IngressBackend class.
        /// </summary>
        public V1beta1IngressBackend()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1IngressBackend class.
        /// </summary>
        /// <param name="backendRules">Serialized HAProxy rules to apply on
        /// server backend including request, response or header rewrite. acls
        /// also can be used.
        /// https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#1</param>
        /// <param name="hostNames">Host names to forward traffic to. If empty
        /// traffic will be forwarded to all subsets instance. If set only
        /// matched hosts will get the traffic. This is an handy way to send
        /// traffic to Specific StatefulSet pod. IE. Setting [web-0] will send
        /// traffic to only web-0 host for this StatefulSet,
        /// https://kubernetes.io/docs/tasks/stateful-application/basic-stateful-set/#creating-a-statefulset</param>
        /// <param name="name">User can specify backend name for using it with
        /// custom acl Otherwise it will be generated</param>
        /// <param name="serviceName">Specifies the name of the referenced
        /// service.</param>
        /// <param name="servicePort">Specifies the port of the referenced
        /// service.</param>
        public V1beta1IngressBackend(IList<string> backendRules = default(IList<string>), IList<string> hostNames = default(IList<string>), string name = default(string), string serviceName = default(string), k8s.Models.IntstrIntOrString servicePort = default(k8s.Models.IntstrIntOrString))
        {
            BackendRules = backendRules;
            HostNames = hostNames;
            Name = name;
            ServiceName = serviceName;
            ServicePort = servicePort;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets serialized HAProxy rules to apply on server backend
        /// including request, response or header rewrite. acls also can be
        /// used.
        /// https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#1
        /// </summary>
        [JsonProperty(PropertyName = "backendRules")]
        public IList<string> BackendRules { get; set; }

        /// <summary>
        /// Gets or sets host names to forward traffic to. If empty traffic
        /// will be forwarded to all subsets instance. If set only matched
        /// hosts will get the traffic. This is an handy way to send traffic to
        /// Specific StatefulSet pod. IE. Setting [web-0] will send traffic to
        /// only web-0 host for this StatefulSet,
        /// https://kubernetes.io/docs/tasks/stateful-application/basic-stateful-set/#creating-a-statefulset
        /// </summary>
        [JsonProperty(PropertyName = "hostNames")]
        public IList<string> HostNames { get; set; }

        /// <summary>
        /// Gets or sets user can specify backend name for using it with custom
        /// acl Otherwise it will be generated
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets specifies the name of the referenced service.
        /// </summary>
        [JsonProperty(PropertyName = "serviceName")]
        public string ServiceName { get; set; }

        /// <summary>
        /// Gets or sets specifies the port of the referenced service.
        /// </summary>
        [JsonProperty(PropertyName = "servicePort")]
        public k8s.Models.IntstrIntOrString ServicePort { get; set; }

    }
}
