// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// LocalTypedReference contains enough information to let you inspect or
    /// modify the referred object.
    /// </summary>
    public partial class V1beta1LocalTypedReference
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1LocalTypedReference class.
        /// </summary>
        public V1beta1LocalTypedReference()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1LocalTypedReference class.
        /// </summary>
        /// <param name="apiVersion">API version of the referent.</param>
        /// <param name="kind">Kind of the referent. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds</param>
        /// <param name="name">Name of the referent. More info:
        /// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names</param>
        public V1beta1LocalTypedReference(string apiVersion = default(string), string kind = default(string), string name = default(string))
        {
            ApiVersion = apiVersion;
            Kind = kind;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets API version of the referent.
        /// </summary>
        [JsonProperty(PropertyName = "apiVersion")]
        public string ApiVersion { get; set; }

        /// <summary>
        /// Gets or sets kind of the referent. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// Gets or sets name of the referent. More info:
        /// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
