// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class V1beta1TLSAuth
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1TLSAuth class.
        /// </summary>
        public V1beta1TLSAuth()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1TLSAuth class.
        /// </summary>
        public V1beta1TLSAuth(string errorPage = default(string), IDictionary<string, string> headers = default(IDictionary<string, string>), string secretName = default(string), string verifyClient = default(string))
        {
            ErrorPage = errorPage;
            Headers = headers;
            SecretName = secretName;
            VerifyClient = verifyClient;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorPage")]
        public string ErrorPage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "headers")]
        public IDictionary<string, string> Headers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secretName")]
        public string SecretName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyClient")]
        public string VerifyClient { get; set; }

    }
}
