// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class V1beta1BasicAuth
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1BasicAuth class.
        /// </summary>
        public V1beta1BasicAuth()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1BasicAuth class.
        /// </summary>
        public V1beta1BasicAuth(string realm = default(string), string secretName = default(string))
        {
            Realm = realm;
            SecretName = secretName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "realm")]
        public string Realm { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secretName")]
        public string SecretName { get; set; }

    }
}
