// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace com.appscode.voyager.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class V1beta1VaultStore
    {
        /// <summary>
        /// Initializes a new instance of the V1beta1VaultStore class.
        /// </summary>
        public V1beta1VaultStore()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1beta1VaultStore class.
        /// </summary>
        public V1beta1VaultStore(string name = default(string), string prefix = default(string))
        {
            Name = name;
            Prefix = prefix;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prefix")]
        public string Prefix { get; set; }

    }
}
